-- EduInsights PostgreSQL Schema

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Profiles table (extending Supabase Auth users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  display_name TEXT,
  school_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Subjects table
CREATE TABLE subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE, -- Supports Unicode Sinhala
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Exam Records table
CREATE TABLE exam_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  year INTEGER NOT NULL,
  subject_id BIGINT REFERENCES subjects(id) NOT NULL,
  total_students INTEGER DEFAULT 0,
  pass_count INTEGER DEFAULT 0,
  fail_count INTEGER DEFAULT 0,
  term INTEGER, -- Nullable for final exams, 1, 2, 3 for term tests
  a_count INTEGER DEFAULT 0,
  b_count INTEGER DEFAULT 0,
  c_count INTEGER DEFAULT 0,
  s_count INTEGER DEFAULT 0,
  w_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  
  CONSTRAINT valid_counts CHECK (total_students >= (pass_count + fail_count)),
  CONSTRAINT valid_grade_counts CHECK (total_students >= (a_count + b_count + c_count + s_count + w_count))
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_records ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can view their own records" ON exam_records FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own records" ON exam_records FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own records" ON exam_records FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own records" ON exam_records FOR DELETE USING (auth.uid() = user_id);

-- Public subjects (everyone can see)
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Subjects are viewable by everyone" ON subjects FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert subjects" ON subjects FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create students table
CREATE TABLE students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  grade INTEGER NOT NULL,
  class_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for students
ALTER TABLE students ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own students" 
ON students FOR ALL 
USING (auth.uid() = user_id);

-- Create student_marks table
CREATE TABLE student_marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE NOT NULL,
  subject_id BIGINT REFERENCES subjects(id) NOT NULL,
  mark INTEGER CHECK (mark >= 0 AND mark <= 100),
  term INTEGER, -- Nullable for final exams, 1, 2, 3 for term tests
  year INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for student_marks
ALTER TABLE student_marks ENABLE ROW LEVEL SECURITY;

-- Policy for student_marks (needs to check if student belongs to user)
CREATE POLICY "Users can manage marks for their students" 
ON student_marks FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM students 
    WHERE students.id = student_marks.student_id 
    AND students.user_id = auth.uid()
  )
);
